on:
  push:
    branches:
    - main
jobs:
  job1:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 更新库
        run: sudo apt update
      - name: 安装shellcheck
        run: sudo apt install shellcheck
      - name: 检查
        run: find . -name "*.sh" -exec shellcheck {} +
  
